### ISSUE TITLE
state.h not found!

### ISSUE THREAD

**Issue by loganwhite** [vigor-nf/vigor#3]
In files `vigor/vignat/nat_flowmanager.c` and `vigor/vigfw/fw_flowmanager.c`, there are `#include "state.h"` preprocessing instructions. But I cannot find the `state.h` file in the repository. Would you please let us know what is inside of this file and where we can get it?

**Comment by necto** [comment]
`state.h`, along with `state.c`, `loop.c`, `loop.h` and a few files ending with '.gen.*' are generated automatically with the code generator located in the `codegen` folder for each NF, based on a `dataspec.ml` file (e.g. https://github.com/vigor-nf/vigor/blob/master/vignat/dataspec.ml) with this make rule: https://github.com/vigor-nf/vigor/blob/master/Makefile#L68
Note that the generated files, besides the C code, contain also VeriFast contracts and proofs, and are checked by VeriFast for correctness: https://github.com/vigor-nf/vigor/blob/master/codegen/generate.sh#L27

**Comment by loganwhite** [comment]
Many thanks, @necto, really appreciate it!
